export default {
  input: {
    'fontFamily': 'Space Mono',
    'fontSize': '24px',
    'lineHeight': 1.5,
    'letterSpacing': '2px',
    'maxWidth': '100%',
    'backgroundColor': 'transparent',
    'borderBottom': '1px solid #fff',
    'borderRadius': 0,
    'borderTop': 0,
    'borderLeft': 0,
    'borderRight': 0,
    'color': 'rgba(255,255,255,0.54)',
    'width': 'calc(100% - 140px)',
    'paddingBottom': '16px',
    '&:focus': {
      outline: 'none',
    },
  },
  textarea: {
    'fontFamily': 'Space Mono',
    'fontSize': '24px',
    'lineHeight': 1.5,
    'letterSpacing': '2px',
    'maxWidth': '100%',
    'height': '50px',
    'backgroundColor': 'transparent',
    'borderBottom': '1px solid #fff',
    'borderRadius': 0,
    'borderTop': 0,
    'borderLeft': 0,
    'borderRight': 0,
    'color': 'rgba(255,255,255,0.54)',
    'width': 'calc(100% - 140px)',
    '&:focus': {
      outline: 'none',
    },
  },
};
