export default {
  input: {
    fontFamily: 'Space Mono',
    backgroundColor: 'transparent',
    borderBottom: '1px solid #fff',
    borderRadius: 0,
    borderTop: 0,
    borderLeft: 0,
    borderRight: 0,
    color: '#fff',
    fontSize: '14px',
    width: '360px',
    padding: '10px',
  },
  textarea: {
    fontFamily: 'Space Mono',
    backgroundColor: 'transparent',
    borderBottom: '1px solid #fff',
    borderRadius: 0,
    borderTop: 0,
    borderLeft: 0,
    borderRight: 0,
    color: '#fff',
    fontSize: '14px',
    width: '360px',
    padding: '10px',
  },
};
