export default [{
  id: 'snapp',
  name: 'Snapp Builder',
  headline: 'Its all about building apps',
  shortDescription: 'Snapp Builder is first of its kind app for building apps. Snapp Builder is first of its kind app for building apps. Snapp Builder is first of its kind app for building apps',
  description: 'Snapp Builder is first of its kind app for building apps',
  duration: '1_YEAR',
  review: {
    companyName: 'Ch Ch Tecnologies',
    avatar: '',
    content: 'Ch Ch Technologies description',
    representative: 'GEORGI_DETELINOV',
    representativeRole: 'FINANCE_CONSULTANT',
  },
  landingImage: null,
  peopleInterest: 0.24,
  trustFactor: 0.14,
  realtimeboardLink: 'https://realtimeboard.com/b/12345',
}, {
  id: 'seemba',
  name: 'Seemba',
  headline: 'Its all about online presence',
  shortDescription: 'Seemba helps SMEs to build their online presence',
  description: 'Seemba helps SMEs to build their online presence',
  duration: '3_YEARS',
  review: {
    companyName: 'Ch Ch Tecnologies',
    avatar: '',
    content: 'Ch Ch Technologies description',
    representative: 'GEORGI_DETELINOV',
    representativeRole: 'FINANCE_CONSULTANT',
  },
  landingImage: null,
  peopleInterest: 0.24,
  trustFactor: 0.14,
  realtimeboardLink: 'https://realtimeboard.com/b/12345',
}, {
  id: 'history-park',
  name: 'History Park',
  headline: 'Its all about history',
  shortDescription: 'History Park is a park of history',
  description: 'Characters that have had created the big part of the European History. Well guess what Bulgaria takes role here in on Balkans with it nation which is several thousand years old. This is History park, it brings Bulgarian and partial Roman history by presenting it in a interactive way and taking you centuries and decades ago. People in the park will be able to experience this time travel, ride horses and shoot with a bow while riding, eat ancient kitchen, leave like the old days, even fight on the arena.',
  duration: '1_MONTH',
  review: {
    companyName: 'Together Bulgaria',
    avatar: '',
    content: 'Working with Stoyan was just an awesome experience. He invested time to learn about out wants and need , he also took time to learn everything needed fo the project Historical Park so he could make the best website for it He was honest and transparent about the process and kept us involved all the time. It was up to Stoyan to really translate everything we talked about in to the website design and to find the best one for this big project.. The end result was just awesome, he did what we had as an idea and done it at the best way. Looking forward to work with Stoyan again.',
    representative: 'GEORGI_DETELINOV',
    representativeRole: 'FINANCE_CONSULTANT',
  },
  landingImage: null,
  metadata: [{
    displayName: '',
    value: null,
  }],
  peopleInterest: 0.24,
  trustFactor: 0.14,
  realtimeboardLink: 'https://realtimeboard.com/b/12345',
  problem: {
    type: 'bullet-points',
    description: 'Imagine Disney Land but instead of the cartoon characters real ones. Characters that have had created the big part of the European History.',
    bulletPoints: [
      'Imagine Disney Land but instead of the cartoon characters real ones. Characters that have had created the big part of the European History.',
      'ad Imagine Disney Land but instead of the cartoon characters real ones. Characters that have had created the big part of the European History.',
    ],
  },
  images: ['image_1_uri', 'image_1_uri', 'image_1_uri'],
}];